//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace human.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string img { get; set; }
        public string cv_title { get; set; }
        public string company_name { get; set; }
        public Nullable<System.DateTime> work_time_from { get; set; }
        public Nullable<System.DateTime> work_time_to { get; set; }
        public Nullable<int> experience_year { get; set; }
        public string current_position { get; set; }
        public string desire_position { get; set; }
        public string desire_job { get; set; }
        public string desire_salary { get; set; }
        public Nullable<int> salary_char_id { get; set; }
        public string desire_work_location { get; set; }
        public string career_goal { get; set; }
        public string education_school_name { get; set; }
        public Nullable<System.DateTime> education_time_from { get; set; }
        public Nullable<System.DateTime> education_time_to { get; set; }
        public string speciality { get; set; }
        public string graduate_level { get; set; }
        public Nullable<int> self_language_id { get; set; }
        public string language_other { get; set; }
        public Nullable<int> skill_id { get; set; }
        public string skill_other { get; set; }
        public string hobby { get; set; }
        public string facebook { get; set; }
        public string idloginsocial { get; set; }
        public Nullable<int> status_active { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Salary_char Salary_char { get; set; }
        public virtual Self_language Self_language { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual User User { get; set; }
    }
}
