//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace human.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class humanEntities1 : DbContext
    {
        public humanEntities1()
            : base("name=humanEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Contact_us> Contact_us { get; set; }
        public virtual DbSet<Employment> Employments { get; set; }
        public virtual DbSet<Listnew> Listnews { get; set; }
        public virtual DbSet<Modnew> Modnews { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Recruit> Recruits { get; set; }
        public virtual DbSet<Salary_char> Salary_char { get; set; }
        public virtual DbSet<Self_language> Self_language { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<User_level> User_level { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Web_language> Web_language { get; set; }
    }
}
