//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace human.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modnew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modnew()
        {
            this.Listnews = new HashSet<Listnew>();
        }
    
        public int id { get; set; }
        public string mod_name { get; set; }
        public string mod_img { get; set; }
        public string description { get; set; }
        public string slug { get; set; }
        public Nullable<int> user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listnew> Listnews { get; set; }
        public virtual User User { get; set; }
    }
}
