//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace human.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int id { get; set; }
        public Nullable<int> listnews_id { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public string content { get; set; }
        public string img { get; set; }
        public Nullable<int> status_active { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Listnew Listnew { get; set; }
        public virtual User User { get; set; }
    }
}
