//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace human.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruit
    {
        public int id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string title { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> sex { get; set; }
        public string job_description { get; set; }
        public string work_location { get; set; }
        public string work_time { get; set; }
        public string holiday { get; set; }
        public string condition { get; set; }
        public Nullable<int> employment_id { get; set; }
        public string education_level { get; set; }
        public string salary { get; set; }
        public Nullable<int> salary_char_id { get; set; }
        public string training_time { get; set; }
        public string welfare { get; set; }
        public string applicable_nationality { get; set; }
        public string selection_process { get; set; }
        public Nullable<int> status_active { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employment Employment { get; set; }
        public virtual Salary_char Salary_char { get; set; }
        public virtual User User { get; set; }
    }
}
